' token.bas - SQL Token Types and Constants
' Part of SQLite Clone - Zanna Basic Implementation

'=============================================================================
' TOKEN CONSTANTS
'=============================================================================

CONST TK_EOF = 0
CONST TK_ERROR = 1
CONST TK_INTEGER = 10
CONST TK_NUMBER = 11
CONST TK_STRING = 12
CONST TK_IDENTIFIER = 13

' Keywords - DDL
CONST TK_CREATE = 20
CONST TK_TABLE = 21
CONST TK_DROP = 22
CONST TK_ALTER = 23
CONST TK_INDEX = 24

' Keywords - DML
CONST TK_SELECT = 30
CONST TK_INSERT = 31
CONST TK_UPDATE = 32
CONST TK_DELETE = 33
CONST TK_INTO = 34
CONST TK_FROM = 35
CONST TK_WHERE = 36
CONST TK_SET = 37
CONST TK_VALUES = 38

' Keywords - Clauses
CONST TK_ORDER = 40
CONST TK_BY = 41
CONST TK_ASC = 42
CONST TK_DESC = 43
CONST TK_LIMIT = 44
CONST TK_OFFSET = 45
CONST TK_GROUP = 46
CONST TK_HAVING = 47
CONST TK_DISTINCT = 48

' Keywords - Joins
CONST TK_JOIN = 50
CONST TK_INNER = 51
CONST TK_LEFT = 52
CONST TK_RIGHT = 53
CONST TK_FULL = 54
CONST TK_OUTER = 55
CONST TK_CROSS = 56
CONST TK_ON = 57

' Keywords - Logical
CONST TK_AND = 60
CONST TK_OR = 61
CONST TK_NOT = 62
CONST TK_IN = 63
CONST TK_IS = 64
CONST TK_LIKE = 65
CONST TK_BETWEEN = 66
CONST TK_EXISTS = 67

' Keywords - Values
CONST TK_NULL = 70
CONST TK_TRUE = 71
CONST TK_FALSE = 72
CONST TK_DEFAULT = 73

' Keywords - Constraints
CONST TK_PRIMARY = 80
CONST TK_FOREIGN = 81
CONST TK_KEY = 82
CONST TK_REFERENCES = 83
CONST TK_UNIQUE = 84
CONST TK_AUTOINCREMENT = 87

' Keywords - Types
CONST TK_INT = 90
CONST TK_INTEGER_TYPE = 91
CONST TK_REAL = 92
CONST TK_TEXT = 93

' Keywords - Transactions
CONST TK_BEGIN = 100
CONST TK_COMMIT = 101
CONST TK_ROLLBACK = 102
CONST TK_TRANSACTION = 103
CONST TK_SAVEPOINT = 104
CONST TK_TO = 105
CONST TK_RELEASE = 106

' Keywords - Other
CONST TK_AS = 110
CONST TK_CASE = 111
CONST TK_WHEN = 112
CONST TK_THEN = 113
CONST TK_ELSE = 114
CONST TK_END = 115
CONST TK_UNION = 116
CONST TK_ALL = 117
CONST TK_CAST = 118

' Operators
CONST TK_PLUS = 140
CONST TK_MINUS = 141
CONST TK_STAR = 142
CONST TK_SLASH = 143
CONST TK_PERCENT = 144
CONST TK_EQ = 145
CONST TK_NE = 146
CONST TK_LT = 147
CONST TK_LE = 148
CONST TK_GT = 149
CONST TK_GE = 150
CONST TK_CONCAT = 151

' Punctuation
CONST TK_LPAREN = 160
CONST TK_RPAREN = 161
CONST TK_COMMA = 162
CONST TK_SEMICOLON = 163
CONST TK_DOT = 164

'=============================================================================
' TOKEN CLASS - Simple data holder
'=============================================================================

CLASS Token
    PUBLIC kind AS INTEGER
    PUBLIC text AS STRING
    PUBLIC lineNum AS INTEGER
    PUBLIC colNum AS INTEGER

    PUBLIC SUB Init(k AS INTEGER, t AS STRING, ln AS INTEGER, col AS INTEGER)
        kind = k
        text = t
        lineNum = ln
        colNum = col
    END SUB
END CLASS
